FROM maven as builder
WORKDIR /app/api
COPY devops-challenge/api/ /app/api
RUN mvn -e package

FROM java
COPY --from=builder /app/api/target/*.jar /usr/bin/app.jar
CMD ["java -jar /usr/bin/app.jar"]  
