version: "3"
services:
  postgres:
    container_name: postgresql
    image: "postgres:13.2"
    ports: 
      - 5432:5432
    env_file:
      - postgres.env
    volumes:
      - database-data:/var/lib/postgresql/data/
  app-back:
    build:
      context: ./
      dockerfile: Dockerfile.back
    depends_on:
        - postgres
    ports: 
        - 8080:80
#  app-front:
#    build:
#      context: ./
#      dockerfile: Dockerfile.front
#    depends_on:
#        - postgres
#        - app-back
#    ports: 
#        - 8080:80
volumes:
  database-data: